# Development override - this file is automatically loaded in development
version: '3.8'

services:
  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking_swap_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Development Redis with exposed port
  redis:
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis_dev_data:/data

  # Development backend with hot reload
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/booking_swap_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_not_for_production
      HEDERA_NETWORK: testnet
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./packages/shared/src:/app/packages/shared/src
    command: npm run dev

  # Development frontend with hot reload
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./packages/shared/src:/app/packages/shared/src
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data: